--select * from ProfileTopics
/****** Object:  Table [dbo].[ProfileTopics]    Script Date: 01/15/2011 17:17:19 ******/
--truncate table [ProfileTopics]
SET IDENTITY_INSERT [dbo].[ProfileTopics] ON
--INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (1, N'Basic Information', 1, 2, 2)
--INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (2, N'Detailed Information', 2, 1, 1)
update ProfileTopics set pt_name='Detailed Information' where pt_id=2
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (3, N'Appearance', 3, 1, 1)
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (4, N'Profession', 5, 1, 1)
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (5, N'Relationship', 4, 1, 1)
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (6, N'Background', 6, 1, 1)
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (7, N'Habits', 7, 1, 1)
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (8, N'About', 9, 1, 98)
INSERT [dbo].[ProfileTopics] ([pt_id], [pt_name], [pt_priority], [pt_editcolumns], [pt_viewcolumns]) VALUES (9, N'Match', 8, 1, 1)
SET IDENTITY_INSERT [dbo].[ProfileTopics] OFF
/****** Object:  Table [dbo].[ProfileQuestions]    Script Date: 01/15/2011 17:17:19 ******/
--select * from ProfileQuestions
SET IDENTITY_INSERT [dbo].[ProfileQuestions] ON
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (1, 3, N'Height', N'Height', N'', N'', 5, 2, 0, 1, 1, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (2, 3, N'Weight', N'Weight', N'', N'', 5, 0, 0, 1, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (3, 3, N'Body Type', N'Body Type', N'', N'', 5, 2, 2, 0, 3, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (4, 5, N'Looking for', N'Looking for', N'', N'', 6, 2, 2, 0, 4, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (5, 3, N'Eyes', N'Eyes', N'', N'', 5, 2, 2, 0, 4, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (6, 3, N'Hair', N'Hair', N'', N'', 5, 2, 2, 0, 5, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (7, 7, N'Smoking', N'Smoking', N'', N'', 5, 2, 2, 0, 1, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (8, 7, N'Drinking', N'Drinking', N'', N'', 5, 2, 2, 0, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (9, 2, N'Title', N'Title', N'Here''s your chance for good first impression. Write something original in 80 chars. That title shows right next to your photo and is the first thing other members will see.', N' (max. 80 chars)', 2, 1, 0, 1, 1, 1, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (10, 8, N'Tell us about you', N'About me', N'Now, tell the others what makes you so unique separates you from the rest. Don''t be shy... now is the time for bragging. Describe your perfect date, hobbies, interests, etc', N' (max. 3333 chars)', 2, 4, 0, 1, 1, 1, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (11, 9, N'What are you looking for?', N'Looking for', N'Tell the others exactly what are you looking for. Chat, flirt, dates, whatever...', N' (max. 3333 chars)', 2, 4, 0, 1, 1, 1, 1, 1, 1, NULL, 0, 0, NULL, NULL)
--INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (12, 8, N'Interests', N'Interests', N'', N'', 6, 5, 0, 0, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (14, 2, N'Skype', N'', N'Skype ID', N'', 1, 7, 0, 0, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (15, 4, N'Education', N'Education', N'', N'', 5, 2, 2, 1, 1, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (16, 4, N'Occupation', N'Occupation', N'', N'', 1, 2, 0, 0, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (17, 4, N'Annual Income', N'Income', N'', N'', 5, 2, 2, 0, 3, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (18, 5, N'Status', N'Status', N'', N'', 5, 2, 2, 0, 1, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (19, 5, N'Has Children', N'Has Children', N'', N'', 5, 2, 2, 0, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (20, 5, N'Wants Children', N'Wants Children', N'', N'', 5, 2, 2, 0, 3, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (21, 6, N'Religion', N'Religion', N'', N'', 5, 2, 2, 0, 1, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (22, 6, N'Ethnicity', N'Ethnicity', N'', N'', 5, 2, 2, 0, 2, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
INSERT [dbo].[ProfileQuestions] ([pq_id], [pt_id], [pq_name], [pq_altname], [pq_description], [pq_hint], [pq_edit_style], [pq_show_style], [pq_search_style], [pq_required], [pq_priority], [pq_requires_approval], [pq_visible_male], [pq_visible_female], [pq_visible_couple], [pq_match_field], [pq_viewpaidonly], [pq_editpaidonly], [pq_parent_question_id], [pq_parent_question_choices]) VALUES (23, 6, N'Political Outlook', N'Political Outlook', N'', N'', 5, 2, 2, 0, 3, 0, 1, 1, 1, NULL, 0, 0, NULL, NULL)
SET IDENTITY_INSERT [dbo].[ProfileQuestions] OFF
