//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezFixUp.Components.Matchmaker {
    
    
    public partial class MatchToFriendContent {
        
        /// <summary>
        /// lbFromSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbFromSearch;
        
        /// <summary>
        /// ibFromFriends control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ibFromFriends;
        
        /// <summary>
        /// pnlContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable pnlContent;
        
        /// <summary>
        /// pnlIcons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell pnlIcons;
        
        /// <summary>
        /// btnSendWinkIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.Buttons.SendWinkIcon btnSendWinkIcon;
        
        /// <summary>
        /// btnSendGiftIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.Buttons.SendGiftIcon btnSendGiftIcon;
        
        /// <summary>
        /// btnSendMsgIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.Buttons.SendMsgIcon btnSendMsgIcon;
        
        /// <summary>
        /// btnMoreIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.Buttons.MoreIcon btnMoreIcon;
    }
}
