//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezFixUp {
    
    
    public partial class ReportUserAbuse {
        
        /// <summary>
        /// LargeBoxStart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.LargeBoxStart LargeBoxStart1;
        
        /// <summary>
        /// ReportAbuseCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.ReportAbuse ReportAbuseCtrl;
        
        /// <summary>
        /// LargeBoxEnd1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ezFixUp.Components.LargeBoxEnd LargeBoxEnd1;
    }
}
